// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plxgbpfgstodsgwbxqri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBseGdicGZnc3RvZHNnd2J4cXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjY4NjgsImV4cCI6MjA3MzU0Mjg2OH0.UogJKyoCctpgCcrVvpUixNsqeuBJfb2U-SVLOhanNxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});